### ISSUE TITLE
Panel & Schematic Placement Wonkiness

### ISSUE THREAD

**Issue by Alex33212** [malte0811/ControlEngineering#1]
In both the control panel designer and the logic workbench, sometimes clicking to place a component will put it one position down and to the right compared to its visual position pre-placement. It seems to most often happen when the cursor position is near the division between snap points.

Versions & Modlist:
MC 1.18.2
Control Engineering 0.0.dev1
Forge 40.0.19
Immersive Engineering 1.18.2-7.1.1-pre.104
JEI 1.18.2-9.5.3.143
Immersive Posts 1.18.2-4.3.0-2_DEV-1

**Comment by malte0811** [comment]
Fixed (not pushed yet) for panels, I'm unable to reproduce it with the logic workbench.

**Comment by malte0811** [comment]
@Alex33212 is this still happening with the logic workbench for you?

**Comment by Alex33212** [comment]
Oh, lemme do some testing; does dev build 2 have the fix above?
