### ISSUE TITLE
[Suggestion] Logic Component Cost Rebalance

### ISSUE THREAD

**Issue by Alex33212** [malte0811/ControlEngineering#10]
The costs of logic components seem a bit high to me, and it makes a lot of circuits hard or impossible to fit within a single cabinet. I'd suggest having the three-input versions cost the same as the 2-input versions, halving the vacuum-tube cost of all logic gates (AND, OR, XOR, etc, plus the comparator) besides the inverter (since it only costs 1), and knocking one vacuum tube off the cost of the RS latch and the Schmitt trigger.

**Comment by malte0811** [comment]
Is the cost the main issue or the cabinet space? If it's the second one I might keep the cost as it is, but say that each tube in the cabinet (somehow) consists of e.g. 2 tube items. I know I considered that at some point, but I can't find the code right now, if I even wrote it in the first place.

For the gates that also exist in IE's logic unit the cost for 2-input version matches the cost used there, so I'd like to avoid changing the "real" cost. (Side note: It looks like that code may already be broken, but if anything it's making things cheaper than they should be)

**Comment by Alex33212** [comment]
It's cost, since only a stack of components can fit in the drawers, which limits circuits to a cost of a stack of either wires or tubes.

**Comment by malte0811** [comment]
I never even thought about the drawer size as a limit for circuit complexity. If that's a bottleneck I can increase the size, I should really do some maths on this. Can you give me some rough gate counts for e.g. the memory you showed on discord?

**Comment by Alex33212** [comment]
Yeah, it's:
- 4 RS latches
- 10 2-input AND gates
- 1 3-input AND gate
- 2 NOR gates
- 4 NOT gates (inverters)
- 10 digitizers

However, that's not the complete circuit as I'd want it; ideally there'd be an extra section with another 4 AND gates and a NOT gate, and configuration of the address-matcher block can take up to two additional inverters, so that'd be a max of 14 2-input AND gates and 7 NOT gates.

Here's the schematic, with the "missing" section outlined in red:
![image](https://user-images.githubusercontent.com/13616305/160297858-c452b9cd-3eca-4d3f-bac7-eb4124002a24.png)
