### ISSUE TITLE
Logic cabinet lighting issue

### ISSUE THREAD

**Issue by Alex33212** [malte0811/ControlEngineering#12]
Relatively minor, but the the clock side of the logic cabinet's model interacts weirdly with smooth lighting, as shown here:
![2022-03-26_15 35 48](https://user-images.githubusercontent.com/13616305/160259258-d47bb754-c735-437b-a95b-dd772f9ff44b.png)

It also seems to vary depending on orientation; when the cabinet is facing north or south, the effect is much stronger than when it's facing east or west.

Versions & Modlist:
MC 1.18.2
Control Engineering 0.0.dev1
Forge 40.0.19
Immersive Engineering 1.18.2-7.1.1-pre.104
JEI 1.18.2-9.5.3.143
Immersive Posts 1.18.2-4.3.0-2_DEV-1

**Comment by malte0811** [comment]
Try enabling `experimentalForgeLightPipelineEnabled` in `forge-client.toml`. Without that option you'll get some weird lighting on IE conveyors as well.

**Comment by Alex33212** [comment]
Ah yep, that fixes it!
