### ISSUE TITLE
Wire Remapper Loop

### ISSUE THREAD

**Issue by Alex33212** [malte0811/ControlEngineering#18]
Might be intended behavior, but when at least two wire remappers have both sides linked to each other, any signals will become "stuck" at the highest value they've been set to.

**Comment by malte0811** [comment]
![2022-03-28_09 47 33](https://user-images.githubusercontent.com/10406104/160351106-cc5de8d6-86e7-45db-9643-227e18bdd6a1.png)

"Intended" might be a bit strong, "accepted" is more accurate. The same happens with "discrete" remappers (see screenshot), it would be hard and annoying to fix. Discrete remappers would be harder than my "integrated" ones, but even for those it's more work than I'm willing to invest.
