### ISSUE TITLE
[Suggestion] Analog Operator Components

### ISSUE THREAD

**Issue by Alex33212** [malte0811/ControlEngineering#19]
Something that'd be useful in logic cabinets (especially in e.g. digital-to-analog converter circuits) is a set of analog operators to complement the digital ones. A good set of operators would be:
- INV (1 input; out is inverse of in) (analogue of NOT)
- MAX (2+ inputs; out is highest in) (analogue of OR)
- MIN (2+ inputs; out is lowest in) (analogue of AND)
- SUM (2+ inputs; out is sum of in, capping at max signal strength) (a different analogue of OR)
- DIFF (2 inputs; out is difference between in) (analogue of XOR)

**Comment by malte0811** [comment]
I've added a few different new analog leafcells in the last commits, I think they should be enough to build most circuits. If you notice anything important I've missed please either open a new issue or post a comment here.
