### ISSUE TITLE
[Suggestion] RGB indecator 

### ISSUE THREAD

**Issue by keifhausin** [malte0811/ControlEngineering#24]
The RGB indicator was a feature in IW, and I feel it will be a great addition, 
especially when combined with the new logic cabinet.

For maximum flexibility, each input color should independently be allowed to use any of the buses, 

> i.e., red is on bus 0 orange, blue is on bus 2 black and green is on bus 3 green.

The component cost should probably be a red, green, and blue dye, and the other components for an indicator.

This Idea could be extended to RGB buttons or timed buttons, having the RGB input channels alongside the output channel.

**Comment by malte0811** [comment]
I didn't really like the RGB indicator in IW, so I'm not going to add it in CE. The control panels are meant to have a bit of a "rugged, heavy industrial" feel (not that I consistently achieve that), while the RGB indicator feels closer to fancy gaming PCs for me. I hope that explanation makes sense.
