### ISSUE TITLE
[Suggestion] Logic Workbench Schematic Item

### ISSUE THREAD

**Issue by Alex33212** [malte0811/ControlEngineering#3]
Some sort of way to save a logic schematic into item form would be quite useful, allowing the saving of schematics to free up a workbench for further use as well as the movement of schematics between logic workbenches.

**Comment by Alex33212** [comment]
Oh, something that came up in the IE discord: it'd be very useful to be able to have blueprint files that exist outside the game itself, so they could be loaded externally and be shared between players.
That's a much bigger scope than this issue though; should I make a new one for this?

**Comment by malte0811** [comment]
I've implemented the schematic items in the commit above. Allowing schematics to be uploaded/exported is primarily a gameplay issue, I currently don't see an "immersive" way to do that. The technical side should be pretty easy, mostly just figuring out how to upload to pastebin or similar in code.
