### ISSUE TITLE
[Suggestion] Vertical Control Panels

### ISSUE THREAD

**Issue by Alex33212** [malte0811/ControlEngineering#4]
A way to place control panels vertically would be pretty nice, letting people make proper master control room setups with walls coated in switches and indicators.

**Comment by malte0811** [comment]
![2022-03-24_08 10 09](https://user-images.githubusercontent.com/10406104/159861792-e226805f-7d21-4005-9964-78524fd8bdd2.png)

Is this what you meant? That's already possible, panels can be placed against walls (and even on the ceiling) and the panel height can be adjusted in the engineer's workbench.

TODO for me: Check that this is properly documented in the manual.

**Comment by Alex33212** [comment]
Ohh, didn't realize that! Guess I hadn't tested it out - the documentation (and item render) definitely suggest horizontal use only, at least to me ^^;
