### ISSUE TITLE
[Suggestion] Configurable Logic Cabinet Ports

### ISSUE THREAD

**Issue by Alex33212** [malte0811/ControlEngineering#6]
It'd be quite useful to be able to use the hammer on various locations on the logic cabinet to switch between power input, bus port, and nothing (similar to accumulators' in/out/blank switch). Personally, I'd recommend the locations to be the top and the bottom half of the right, back, and left, with the clock input moved to the bottom part of the front.

**Comment by malte0811** [comment]
I don't think I'll implement the full flexibility you suggested, especially since some of the spots you mention have either decoration or a purpose already. I may look into allowing the cabinet to be mirrored though; so clock on the right, bus on the left. That might already help a little.

**Comment by Alex33212** [comment]
Oh yeah, mirroring would definitely be a big help on its own! Honestly, that plus maybe a bus port on the top would probably cover most use cases.
